name: Preprocess Raw Data like artifact to wandb

on:
  workflow_run:
    workflows: ["Load Raw Data like artifact to wandb"]
    branches: [main]
    types: 
      - completed
  push:
    branches:
      - main
    paths:
      - 'src/data/preprocess.py'

jobs:
  preprocess_data:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest
    env:
      WANDB_API_KEY: ${{ secrets.WANDB_API_KEY }}
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    - name: Set up Python
      uses: actions/setup-python@v5
      id: setup
      with:
        python-version: '3.11'
        cache: 'pip'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Login to WandB
      run: wandb login ${{ secrets.WANDB_API_KEY }}
    - name: Run preprocess.py
      run: python src/data/preprocess.py --IdExecution ${{ github.run_number }}