name: Login to WandB

on:
  workflow_dispatch: # Allows manual execution only

jobs:
  login:
    runs-on: ubuntu-latest
    env:
      WANDB_API_KEY: ${{ secrets.WANDB_API_KEY }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        id: setup
        with:
          python-version: '3.11'
          cache: 'pip'
      - name: Install WandB
        run: pip install wandb==0.15.4
      - name: Login to WandB
        env:
          WANDB_API_KEY: ${{ secrets.WANDB_API_KEY }}
        run: wandb login $WANDB_API_KEY
